version: "3.8"

services:
    main:
        build:
            context: .
            dockerfile: Dockerfile
        command: "php artisan serve --host=0.0.0.0"
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - db

    db:
        platform: linux/x86_64
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: ENV.DB_DATABASE
            MYSQL_ROOT: ENV.DB_USERNAME
            MYSQL_ROOT_PASSWORD: ENV.DB_PASSWORD
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3307:3306
        # user: 1000:1000
